# This JSON patch adds the  necessary annotation, port definitions and
# arguments to the PMEM-CSI node pod.

# PMEM-CSI:
- op: add
  path: /spec/template/metadata/annotations
  value:
    pmem-csi.intel.com/scrape: containers
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
  - name: metrics
    containerPort: 10010
- op: add
  path: /spec/template/spec/containers/0/command/-
  value: -metricsListen=:10010
- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    # If the PMEM-CSI driver is able to serve metrics,
    # then it is alive, for some definition of "alive".
    #
    # In particular this does *not covers capacity
    # checking, because that needs to take a lock
    # which can take an unpredictable amount of time
    # when there is an operation in progress like
    # scrubbing a volume.
    httpGet:
      scheme: HTTP
      path: /metrics/simple
      port: metrics
    # Allow it to for a total duration of one minute.
    # This is conservative because the probe is new.
    failureThreshold: 6
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
- op: add
  path: /spec/template/spec/containers/0/startupProbe
  value:
    httpGet:
      scheme: HTTP
      path: /metrics/simple
      port: metrics
    # Startup may be slower when LVM needs to be set up first.
    # Check more frequently to get it into a ready state quickly.
    failureThreshold: 300
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 5

# TODO: node-driver-registrar once it has metrics support.

# external-provisioner:
- op: add
  path: /spec/template/metadata/annotations
  value:
    pmem-csi.intel.com/scrape: containers
- op: add
  path: /spec/template/spec/containers/2/ports
  value:
  - name: metrics
    containerPort: 10011
- op: add
  path: /spec/template/spec/containers/2/args/-
  value: --metrics-address=:10011
- op: add
  path: /spec/template/spec/containers/2/livenessProbe
  value:
    # If the provisioner is able to serve metrics,
    # then it is alive.
    httpGet:
      scheme: HTTP
      path: /metrics
      port: metrics
    # Same settings as for driver because the provisioner
    # waits for the driver.
    failureThreshold: 6
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
- op: add
  path: /spec/template/spec/containers/2/startupProbe
  value:
    httpGet:
      scheme: HTTP
      path: /metrics
      port: metrics
    failureThreshold: 300
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 5
