# This JSON patch adds the  necessary annotation, port definitions and
# arguments to the PMEM-CSI controller pod.

# PMEM-CSI:
- op: add
  path: /spec/template/metadata/annotations
  value:
    pmem-csi.intel.com/scrape: containers
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
  - name: metrics
    containerPort: 10010
- op: add
  path: /spec/template/spec/containers/0/command/-
  value: -metricsListen=:10010
- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    # If the PMEM-CSI driver is able to serve metrics,
    # then it is alive.
    httpGet:
      scheme: HTTP
      path: /metrics/simple
      port: metrics
    # Allow it to for a total duration of one minute.
    # This is conservative because the probe is new.
    failureThreshold: 6
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
- op: add
  path: /spec/template/spec/containers/0/startupProbe
  value:
    httpGet:
      scheme: HTTP
      path: /metrics/simple
      port: metrics
    # Check more frequently while the container starts up
    # to get it into a ready state quickly.
    failureThreshold: 60
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 5
